version: '3.9'
services:
  server:
    image: 'nguyentrantrung/embedded_system_iot_server:latest'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512m
    volumes:
      - ./db:/db
    environment:
      - CONFIG_FILE_PATH=./configs.json
    ports:
      - 8080:8080
      - 8081:8081
      # MQTT v5.0
      - 8083:8083
